version: '1.0'

services:
  alice:
    build: .
    networks:
      - mynet
    ports:
      - "8080:8080"
  bob:
    build: .
    networks:
      - mynet
    depends_on:
      - alice

networks:
  mynet:
    driver: bridge